--Kategorien weitere aus Filter hinzufügen
INSERT INTO CATEGORY (name) VALUES ('Fruestueck')
INSERT INTO CATEGORY (name) VALUES ('Snacks')
INSERT INTO CATEGORY (name) VALUES ('Vorspeise')
INSERT INTO CATEGORY (name) VALUES ('Hauptgericht')
INSERT INTO CATEGORY (name) VALUES ('Dessert')
-- Einheiten
INSERT INTO MEASURE (name_long,name_short) VALUES ('Esslöffel','EL')
INSERT INTO MEASURE (name_long,name_short) VALUES ('Teelöffel','TL')
INSERT INTO MEASURE (name_long,name_short) VALUES ('Gramm','g')
INSERT INTO MEASURE (name_long,name_short) VALUES ('Kilogramm','kg')
INSERT INTO MEASURE (name_long,name_short) VALUES ('Tasse','t')
INSERT INTO MEASURE (name_long,name_short) VALUES ('Messerspitze','ms')
INSERT INTO MEASURE (name_long,name_short) VALUES ('Einheit','')
INSERT INTO MEASURE (name_long,name_short) VALUES ('Liter','l')
INSERT INTO MEASURE (name_long,name_short) VALUES ('Milliliter','ml')
INSERT INTO MEASURE (name_long,name_short) VALUES ('Tropf','trp.')
-- Zutaten
INSERT INTO INGREDIENT ( name) VALUES ('Gemüsebouillon')
INSERT INTO INGREDIENT ( name) VALUES ('Ananas, in Sirup, Konserve, abgetropft')
INSERT INTO INGREDIENT ( name) VALUES ('Ananas, mit Süssungsmittel, Konserve, abgetropft')
INSERT INTO INGREDIENT ( name) VALUES ('Apfel, geschaelt, getrocknet')
INSERT INTO INGREDIENT ( name) VALUES ('Aprikose, getrocknet')
INSERT INTO INGREDIENT ( name) VALUES ('Béchamelsauce, hausgemacht')
INSERT INTO INGREDIENT ( name) VALUES ('Bierwurst')
INSERT INTO INGREDIENT ( name) VALUES ('Birne, getrocknet')
INSERT INTO INGREDIENT ( name) VALUES ('Fruechte, getrocknet')
INSERT INTO INGREDIENT ( name) VALUES ('Gorgonzola')
INSERT INTO INGREDIENT ( name) VALUES ('Kirsch')
INSERT INTO INGREDIENT ( name) VALUES ('Parmesan')
INSERT INTO INGREDIENT ( name) VALUES ('Pferd, Filet, roh')
INSERT INTO INGREDIENT ( name) VALUES ('Pfirsich, gelb, roh')
--Zeile 15
INSERT INTO INGREDIENT ( name) VALUES ('Kuerbis')
INSERT INTO INGREDIENT ( name) VALUES ('Dinkelvollkornmehl')
INSERT INTO INGREDIENT ( name) VALUES ('Salz')
INSERT INTO INGREDIENT ( name) VALUES ('Leinsamen')
INSERT INTO INGREDIENT ( name) VALUES ('Kuerbiskerne')
INSERT INTO INGREDIENT ( name) VALUES ('Trockenhefe')
INSERT INTO INGREDIENT ( name) VALUES ('Zucchetti, gerieben')
INSERT INTO INGREDIENT ( name) VALUES ('Hackfleisch')
INSERT INTO INGREDIENT ( name) VALUES ('Zwiebel, gehackt')
INSERT INTO INGREDIENT ( name) VALUES ('Curry')