--Kategorien
INSERT INTO CATEGORY (name) VALUES ('Fruehstueck')
INSERT INTO CATEGORY (name) VALUES ('Snacks')
INSERT INTO CATEGORY (name) VALUES ('Vorspeise')
INSERT INTO CATEGORY (name) VALUES ('Hauptgericht')
INSERT INTO CATEGORY (name) VALUES ('Dessert')
-- Einheiten
INSERT INTO MEASURE (name_long,name_short) VALUES ('Esslöffel','EL')
INSERT INTO MEASURE (name_long,name_short) VALUES ('Teelöffel','TL')
INSERT INTO MEASURE (name_long,name_short) VALUES ('Gramm','g')
INSERT INTO MEASURE (name_long,name_short) VALUES ('Kilogramm','kg')
INSERT INTO MEASURE (name_long,name_short) VALUES ('Tasse','t')
INSERT INTO MEASURE (name_long,name_short) VALUES ('Messerspitze','ms')
INSERT INTO MEASURE (name_long,name_short) VALUES ('Einheit','')
INSERT INTO MEASURE (name_long,name_short) VALUES ('Liter','l')
INSERT INTO MEASURE (name_long,name_short) VALUES ('Milliliter','ml')
INSERT INTO MEASURE (name_long,name_short) VALUES ('Tropf','trp.')
-- Zutaten
INSERT INTO INGREDIENT ( name) VALUES ('Kuerbis')
INSERT INTO INGREDIENT ( name) VALUES ('Dinkelvollkornmehl')
INSERT INTO INGREDIENT ( name) VALUES ('Salz')
INSERT INTO INGREDIENT ( name) VALUES ('Kuerbiskerne')
INSERT INTO INGREDIENT ( name) VALUES ('Trockenhefe')
INSERT INTO INGREDIENT ( name) VALUES ('Bouillon')
INSERT INTO INGREDIENT ( name) VALUES ('Zwiebel')
INSERT INTO INGREDIENT ( name) VALUES ('Gewuerze nach Belieben')
INSERT INTO INGREDIENT ( name) VALUES ('Creme fraiche')
INSERT INTO INGREDIENT ( name) VALUES ('Butterguetzli')
INSERT INTO INGREDIENT ( name) VALUES ('Amaretti')
INSERT INTO INGREDIENT ( name) VALUES ('Zitrone')
INSERT INTO INGREDIENT ( name) VALUES ('Zucker')
INSERT INTO INGREDIENT ( name) VALUES ('Bier')
--Zeile 15
INSERT INTO INGREDIENT ( name) VALUES ('Rotkabis')
INSERT INTO INGREDIENT ( name) VALUES ('Limette')
INSERT INTO INGREDIENT ( name) VALUES ('Rohzucker')
INSERT INTO INGREDIENT ( name) VALUES ('Sambal Oelek')
INSERT INTO INGREDIENT ( name) VALUES ('Tortillas')
INSERT INTO INGREDIENT ( name) VALUES ('Guacamole')
INSERT INTO INGREDIENT ( name) VALUES ('Red Kidney Bohnen')
INSERT INTO INGREDIENT ( name) VALUES ('Pfeffer')
INSERT INTO INGREDIENT ( name) VALUES ('rote Peperoni')
INSERT INTO INGREDIENT ( name) VALUES ('roter Traubensaft')
--Zeile 25
INSERT INTO INGREDIENT ( name) VALUES ('schwarze Linsen')
INSERT INTO INGREDIENT ( name) VALUES ('Lachsrückenfilet')
INSERT INTO INGREDIENT ( name) VALUES ('Rüebli')
INSERT INTO INGREDIENT ( name) VALUES ('Radiesli')
INSERT INTO INGREDIENT ( name) VALUES ('Weizenmehl')
INSERT INTO INGREDIENT ( name) VALUES ('Milch')
INSERT INTO INGREDIENT ( name) VALUES ('Wasser')
INSERT INTO INGREDIENT ( name) VALUES ('Knoblauchzehen')
INSERT INTO INGREDIENT ( name) VALUES ('Tomaten')
INSERT INTO INGREDIENT ( name) VALUES ('Gurke')
--Zeile 35
INSERT INTO INGREDIENT ( name) VALUES ('Feta')
INSERT INTO INGREDIENT ( name) VALUES ('Oliven')
INSERT INTO INGREDIENT ( name) VALUES ('Jasmin Reis')
INSERT INTO INGREDIENT ( name) VALUES ('Eier')
INSERT INTO INGREDIENT ( name) VALUES ('Himbeeren tk')
INSERT INTO INGREDIENT ( name) VALUES ('weisse Schokolade')
INSERT INTO INGREDIENT ( name) VALUES ('Butter')


