--Kategorien
INSERT INTO CATEGORY (name) VALUES ('Abendessen')
INSERT INTO CATEGORY (name) VALUES ('Frühstück')
INSERT INTO CATEGORY (name) VALUES ('zVieri')
INSERT INTO CATEGORY (name) VALUES ('zNüni')
INSERT INTO CATEGORY (name) VALUES ('zMittag')
INSERT INTO CATEGORY (name) VALUES ('zMittnehmen')
-- Einheiten
INSERT INTO MEASURE (name_long,name_short) VALUES ('Esslöffel','EL')
INSERT INTO MEASURE (name_long,name_short) VALUES ('Teelöffel','TL')
INSERT INTO MEASURE (name_long,name_short) VALUES ('Gramm','g')
INSERT INTO MEASURE (name_long,name_short) VALUES ('Kilogramm','kg')
INSERT INTO MEASURE (name_long,name_short) VALUES ('Tasse','t')
INSERT INTO MEASURE (name_long,name_short) VALUES ('Messerspitze','ms')
INSERT INTO MEASURE (name_long,name_short) VALUES ('Einheit','')
INSERT INTO MEASURE (name_long,name_short) VALUES ('Liter','l')
INSERT INTO MEASURE (name_long,name_short) VALUES ('Milliliter','ml')
INSERT INTO MEASURE (name_long,name_short) VALUES ('Tropf','trp.')
-- Zutaten
INSERT INTO INGREDIENT ( name) VALUES ('Ananas, in Ananassaft, Konserve, abgetropft')
INSERT INTO INGREDIENT ( name) VALUES ('Ananas, in Ananassaft, Konserve, nicht abgetropft')
INSERT INTO INGREDIENT ( name) VALUES ('Ananas, in Sirup, Konserve, abgetropft')
INSERT INTO INGREDIENT ( name) VALUES ('Ananas, mit Süssungsmittel, Konserve, abgetropft')
INSERT INTO INGREDIENT ( name) VALUES ('Apfel, gedünstet, abgetropft (ohne Zugabe von Zucker)')
INSERT INTO INGREDIENT ( name) VALUES ('Apfel, geschält, getrocknet')
INSERT INTO INGREDIENT ( name) VALUES ('Apfelkuchen, hausgemacht, gebacken (mit Kuchenteig)')
INSERT INTO INGREDIENT ( name) VALUES ('Aprikose, gedünstet, abgetropft (ohne Zugabe von Zucker)')
INSERT INTO INGREDIENT ( name) VALUES ('Aprikose, getrocknet')
INSERT INTO INGREDIENT ( name) VALUES ('Béchamelsauce, hausgemacht')
INSERT INTO INGREDIENT ( name) VALUES ('Beeren (Durchschnitt), gekocht (ohne Zugabe von Zucker)')
INSERT INTO INGREDIENT ( name) VALUES ('Bierwurst')
INSERT INTO INGREDIENT ( name) VALUES ('Birne, gedünstet, abgetropft (ohne Zugabe von Zucker)')
INSERT INTO INGREDIENT ( name) VALUES ('Birne, getrocknet')
INSERT INTO INGREDIENT ( name) VALUES ('Früchte (Durchschnitt), gekocht (ohne Zugabe von Zucker)')
INSERT INTO INGREDIENT ( name) VALUES ('Früchte (Durchschnitt), getrocknet')
INSERT INTO INGREDIENT ( name) VALUES ('Gorgonzola')
INSERT INTO INGREDIENT ( name) VALUES ('Kirsch')
INSERT INTO INGREDIENT ( name) VALUES ('Kirsche, gedünstet, abgetropft (ohne Zugabe von Zucker)')
INSERT INTO INGREDIENT ( name) VALUES ('Parmesan')
INSERT INTO INGREDIENT ( name) VALUES ('Pferd, Filet, roh')
INSERT INTO INGREDIENT ( name) VALUES ('Pfirsich, gelb, roh')
INSERT INTO INGREDIENT ( name) VALUES ('Pfirsich, in Sirup, Konserve, abgetropft')
INSERT INTO INGREDIENT ( name) VALUES ('Pfirsich, mit Süssungsmittel, Konserve, abgetropft')